### ISSUE TITLE
Not working on Express 5.0.0

### ISSUE THREAD

**Issue by skyhancloud** [matthiaaas/express-file-routing#38]
When I try to use `express@5.0.0` with `express-file-routing` I get the error `TypeError: app[methodKey] is not a function`. It gives this error because of line 50 in https://github.com/matthiaaas/express-file-routing/blob/main/src/router.ts. As far as I can see, if the methodKey is `ws`, it gives this error because `app['ws']` returns undefined. In previous versions there was no such problem, but in 5.0.0 there is no app.ws.

**Comment by skyhancloud** [comment]
@matthiaaas

**Comment by matthiaaas** [comment]
Thank you for the issue @chimpdev. Can you provide a sandbox/repo for reproduction for this type error?

**Comment by skyhancloud** [comment]
> Thank you for the issue @chimpdev. Can you provide a sandbox/repo for reproduction for this type error?

You can look at this repository https://github.com/discordplace/lantern

https://github.com/discordplace/lantern/blob/main/server/lib/express/createServer.js

**Comment by matthiaaas** [comment]
Unfortunately, I am unable to reproduce the issue from the project provided. If you could create a minimal repro with TypeScript, that would be immensely helpful @chimpdev

**Comment by skyhancloud** [comment]
> Unfortunately, I am unable to reproduce the issue from the project provided. If you could create a minimal repro with TypeScript, that would be immensely helpful @chimpdev

The error was caused by using router instead of createRouter. sorry for wasting your time <3 
this was fixed in the commit https://github.com/discordplace/lantern/commit/9d5f7bc44a36201bf02e80fdba60907c2ce7aca7

**Comment by matthiaaas** [comment]
Thank you for the quick response and great to see the issue being resolved for you.

Still, I will put this issue into further consideration since both the router and createRouter APIs should be interchangeably appliable. Might also be an issue of `express-ws` not correctly overriding the types for `express.Router` instances for the upcoming Express version.
